version: '2'
services:
  jenkins:
    user: root
    image: 'jenkinsci/blueocean'
    ports:
      - '80:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
volumes:
  jenkins_data:
    driver: local