version: '2'
services:
  jenkins:
    user: root
    image: 'jenkins/jenkins'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'jenkins_data:/bitnami'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_data:
    driver: local